#!/usr/bin/env python3
"""Generate src/schema.h from a pg_dump schema file.

Parses the CREATE TABLE body and the CREATE INDEX statements so the C++ side
never has a hand-copied column list to drift out of sync.
"""
import re
import sys
import pathlib

TEXT_TYPES = {"text", "character varying", "varchar", "char", "character"}


def main() -> int:
    here = pathlib.Path(__file__).resolve().parent.parent
    sql_path = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else here / "contracts_schema.sql"
    out_path = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else here / "src" / "schema.h"
    sql = sql_path.read_text(encoding="utf-8", errors="replace")

    m = re.search(r"CREATE TABLE\s+(?:public\.)?(\w+)\s*\((.*?)\n\);", sql, re.S)
    if not m:
        print("error: no CREATE TABLE found in", sql_path, file=sys.stderr)
        return 1
    table, body = m.group(1), m.group(2)

    cols = []
    for raw in body.split("\n"):
        line = raw.strip().rstrip(",")
        if not line or line.startswith("--"):
            continue
        parts = line.split(None, 1)
        if len(parts) != 2:
            continue
        name, coltype = parts[0], parts[1].strip()
        cols.append((name, coltype, coltype.lower() in TEXT_TYPES))

    idx_cols = []
    for im in re.finditer(r"CREATE INDEX\s+\w+\s+ON\s+(?:public\.)?\w+\s+USING\s+btree\s*\(([^)]+)\)", sql, re.I):
        col = im.group(1).strip().replace('"', "")
        # Single bare columns only -- multi-column and expression indexes
        # (lower(x), a DESC) are left to the reference dump.
        if re.fullmatch(r"\w+", col) and col not in idx_cols:
            idx_cols.append(col)

    def cstr(s: str) -> str:
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    lines = [
        "// Generated by tools/gen_schema.py from %s -- do not edit by hand." % sql_path.name,
        "#pragma once",
        "",
        "namespace schema {",
        "",
        "struct ColDef {",
        "    const char* name;",
        "    const char* sql_type;",
        "    bool is_text;  // non-text columns need FORCE_NULL so quoted \"\" loads as NULL",
        "};",
        "",
        "inline constexpr const char* kDefaultTable = %s;" % cstr(table),
        "",
        "inline constexpr ColDef kColumns[] = {",
    ]
    for name, coltype, is_text in cols:
        lines.append("    {%s, %s, %s}," % (cstr(name), cstr(coltype), "true" if is_text else "false"))
    lines += [
        "};",
        "inline constexpr int kColumnCount = %d;" % len(cols),
        "",
        "// Columns indexed in the reference database. Built after the bulk load.",
        "inline constexpr const char* kIndexColumns[] = {",
    ]
    for c in idx_cols:
        lines.append("    %s," % cstr(c))
    lines += [
        "};",
        "inline constexpr int kIndexColumnCount = %d;" % len(idx_cols),
        "",
        "}  // namespace schema",
        "",
    ]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print("wrote %s: %d columns, %d indexes (table %s)" % (out_path, len(cols), len(idx_cols), table))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
